### ISSUE TITLE
[BUG] Client crashes upon joining a server.

### ISSUE THREAD

**Issue by matthe815** [matthe815/matthews-difficulty-mod#13]
**Describe the bug**
Game crashes upon joining server(?).

**To Reproduce**
1. Join a server.
2. Crash.

**Logs**
`
[15:14:43] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@77e9329c:
java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at difficultymod.temperature.Temp.GetTemperature(Temp.java:89) ~[Temp.class:?]
	at difficultymod.temperature.Temp.HasChanged(Temp.java:41) ~[Temp.class:?]
	at difficultymod.events.LivingEvent.Update(LivingEvent.java:106) ~[LivingEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_LivingEvent_Update_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
[15:14:43] [Server thread/ERROR] [FML]: Index: 3 Listeners:
[15:14:43] [Server thread/ERROR] [FML]: 0: NORMAL
[15:14:43] [Server thread/ERROR] [FML]: 1: ASM: class mrriegel.instantunify.InstantUnify player(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 2: ASM: crafttweaker.mc1120.events.CommonEventHandler@5478c1fd onPlayerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 3: ASM: difficultymod.events.LivingEvent@60e1535f Update(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 4: ASM: difficultymod.events.LivingEvent@60e1535f livingUpdate(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 5: ASM: class ichttt.mods.firstaid.common.EventHandler tickPlayers(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 6: ASM: me.ichun.mods.ichunutil.common.core.event.EventHandlerServer@40812574 onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 7: ASM: gigaherz.toolbelt.slot.ExtensionSlotBelt$EventHandlers@2a8c907c entityTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 8: ASM: net.blay09.mods.netherportalfix.NetherPortalFix@abea61e onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 9: ASM: org.orecruncher.dsurround.server.services.EnvironmentService@46c68611 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 10: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@220cdfd8 tickStart(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[15:14:43] [Server thread/ERROR] [FML]: 11: ASM: com.creativemd.creativecore.common.event.CreativeTickHandler@25ff2034 onEventTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[15:14:43] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:61178
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at difficultymod.temperature.Temp.GetTemperature(Temp.java:89) ~[Temp.class:?]
	at difficultymod.temperature.Temp.HasChanged(Temp.java:41) ~[Temp.class:?]
	at difficultymod.events.LivingEvent.Update(LivingEvent.java:106) ~[LivingEvent.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_LivingEvent_Update_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:365) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:190) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
`

**Comment by matthe815** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Crash when connecting to server - see attached logs](https://trello.com/c/zjKknnGH/100-crash-when-connecting-to-server-see-attached-logs)
